2013-01-17 17:40:03
Traceback (most recent call last):
  File "./sftp/threads.py", line 16, in run_with_except_hook
  File "./sftp/threads.py", line 101, in handler
  File "./sftp/commands.py", line 232, in run
  File "./sftp/commands.py", line 338, in make_connection
  File "./sftp/sftp_transport.py", line 413, in ls
NotFoundError: File not found
2013-01-17 17:41:18
Traceback (most recent call last):
  File "./sftp/threads.py", line 16, in run_with_except_hook
  File "./sftp/threads.py", line 101, in handler
  File "./sftp/commands.py", line 232, in run
  File "./sftp/commands.py", line 338, in make_connection
  File "./sftp/sftp_transport.py", line 413, in ls
NotFoundError: File not found
2013-01-17 17:41:29
Traceback (most recent call last):
  File "./sftp/threads.py", line 16, in run_with_except_hook
  File "./sftp/threads.py", line 101, in handler
  File "./sftp/commands.py", line 232, in run
  File "./sftp/commands.py", line 338, in make_connection
  File "./sftp/sftp_transport.py", line 413, in ls
NotFoundError: File not found
